### ISSUE TITLE
It seams like `Hook (Future e a) b` is equivalent to `ContT a (Future e) b`

### ISSUE THREAD

**Issue by safareli** [fluture-js/fluture-hooks#17]
I was looking at this lib and noticed that the Hook structure is Continuation monad.

**Comment by Avaq** [comment]
Hi. Why did you close this issue? Did you realize it's not true? Because I think it is. :P

This library is essentially a tagged constructor wrapper around [callgebra](https://github.com/fluture-js/callgebra), which I believe is just an implementation of the continuation Monad.

The only thing that makes it Fluture -specific is the Alt instance on `ParallelHook (Future e a) b`:

https://github.com/fluture-js/fluture-hooks/blob/e2fd32742a3b1bc9cd0922ff1610395af8800409/index.js#L158-L226

----

Shall I transfer this issue to a Discussion?
